name: snakegame
description: Simple snake game in Dart.
version: 1.0.0
repository: https://github.com/Ynfuien/snake-dart

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  sdl2: ^1.5.3
  win32: ^5.0.6

dev_dependencies:
  lints: ^2.0.0
